CREATE TABLE public."COMPONENTLICENSES" (
    "COMPONENTID" bigint NOT NULL,
    "LICENSE_ID" bigint,
    "LICENSE" character varying(255),
    "LICENSE_EXPRESSION" text,
    "LICENSE_URL" character varying(255),
    "ORDINALITY" bigint NOT NULL CHECK ("ORDINALITY" > 0),
    "CONCLUDED" boolean DEFAULT false NOT NULL
);

INSERT INTO public."COMPONENTLICENSES" (
    "COMPONENTID",
    "LICENSE_ID",
    "LICENSE",
    "LICENSE_EXPRESSION",
    "LICENSE_URL",
    "CONDLUDED"
) SELECT "ID", "LICENSE_ID", "LICENSE", "LICENSE_EXPRESSION", "LICENSE_URL", 1, false FROM public."COMPONENT";

ALTER TABLE ONLY public."COMPONENTLICENSES"
    ADD CONSTRAINT "COMPONENTLICENSE_PK" PRIMARY KEY ("COMPONENTID", "LICENSE_ID");

ALTER TABLE ONLY public."COMPONENTLICENSES"
    ADD CONSTRAINT "COMPONENTS_VULNERABILITIES_FK1" FOREIGN KEY ("COMPONENTID") REFERENCES public."COMPONENT"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public."COMPONENTLICENSES"
    ADD CONSTRAINT "COMPONENTS_VULNERABILITIES_FK2" FOREIGN KEY ("LICENSE_ID") REFERENCES public."LICENSE"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE public."COMPONENT" DROP CONSTRAINT "COMPONENT_FK3";

ALTER TABLE public."COMPONENT" DROP ("LICENSE_ID", "LICENSE", "LICENSE_EXPRESSION", "LICENSE_URL");
